import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#004182',
        'primary-container': '#0058ac',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#a9c7ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#b8d1ff',
        'on-primary-fixed': '#001b3d',
        'on-primary-fixed-variant': '#00468c',
        secondary: '#006970',
        'secondary-container': '#7af1fc',
        'secondary-fixed': '#7df4ff',
        'secondary-fixed-dim': '#5dd8e2',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#006e75',
        'on-secondary-fixed': '#002022',
        'on-secondary-fixed-variant': '#004f54',
        tertiary: '#004d10',
        'tertiary-container': '#13671f',
        'tertiary-fixed': '#a3f69c',
        'tertiary-fixed-dim': '#88d982',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#91e38b',
        'on-tertiary-fixed': '#002204',
        'on-tertiary-fixed-variant': '#005312',
        surface: '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'surface-variant': '#e0e3e5',
        'surface-tint': '#005db6',
        'on-surface': '#191c1e',
        'on-surface-variant': '#424752',
        'on-background': '#191c1e',
        background: '#f7f9fb',
        outline: '#727784',
        'outline-variant': '#c2c6d4',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#a9c7ff',
      },
      fontFamily: {
        headline: ['Newsreader', 'Playfair Display', 'serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      animation: {
        'fade-up': 'fadeUp 0.6s ease-out forwards',
        'fade-in': 'fadeIn 0.8s ease-out forwards',
        'pulse-slow': 'pulse 3s ease-in-out infinite',
        float: 'float 6s ease-in-out infinite',
      },
      keyframes: {
        fadeUp: {
          from: { opacity: '0', transform: 'translateY(24px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-12px)' },
        },
      },
      boxShadow: {
        'primary-sm': '0 4px 16px rgba(0,65,130,0.08)',
        'primary-md': '0 8px 32px rgba(0,65,130,0.12)',
        'primary-lg': '0 16px 48px rgba(0,65,130,0.16)',
        glass: '0 8px 32px rgba(0,65,130,0.06)',
      },
    },
  },
  plugins: [],
};

export default config;
